### ISSUE TITLE
[PriorTeamNote]-Bug: On login, user sees events from other users

### ISSUE THREAD

**Issue by SELord** [SELord/Schedule-it#1]
When a user logs into the site, they should only be able to see their own events, not all the other user's events as well. View need to be user specific.

**Comment by victoriaderidder** [comment]
I have narrowed this bug down to a SQL query issue in load.php and therefore we are reassigning it.

**Comment by SaeHyoungOh** [comment]
Completely rewrote load.php to conform with reservation.php and to use functions from dbquery.php.

Works on both Chrome and Firefox
