### ISSUE TITLE
[PriorTeamNote]-ToDo: Event creator management page

### ISSUE THREAD

**Issue by SELord** [SELord/Schedule-it#20]
Event management page for creator to see who has accepted, declined, or not responded.

**Comment by victoriaderidder** [comment]
"Need manage events page for the creator so the person who created the event can see who signed up for the events, how many, etc. which can also be used in the polling feature. Here’s a screenshot from the example Don showed us of Doodle where the date of each slot is across the top, the invitees are along the left, and he (as the creator) can see who said they could attend each slot and the top row counts the number of people who selected that slot so if the creator only wanted to host 1 slot, he could pick the one with the most check marks and delete the other slots."
