### ISSUE TITLE
Bug: homepage.php does not work on Chrome

### ISSUE THREAD

**Issue by SaeHyoungOh** [SELord/Schedule-it#27]
I believe the exact problem location is right after login.php authenticates the user / builds the session variables / redirects to homepage.php.
The session variables are empty on homepage.php at this point, though the session id is the same and user was authenticated + session variables were filled in login.php

**Comment by SaeHyoungOh** [comment]
It works on Sae Hyoung's computer as of 4/21/2020

**Comment by SELord** [comment]
This does not seem to be an issue anymore. Closing bug for now, but if this starts occurring again, we can re-open.
