### ISSUE TITLE
[PriorTeamNote]-ToDo: Add message/comment functionality to slot

### ISSUE THREAD

**Issue by SELord** [SELord/Schedule-it#6]
Unable to delete a message/comment or add a new message/comment - can only edit the current slot you're reserved to.

**Comment by SELord** [comment]
Per chat with client on 4/9, the intent is not to be able to continuously add and remove comments to the time slot. This is not supposed to be a message board. Per Don, the intent is to be able to upload a file and short message to the group when reserving your time slot.

**Comment by SaeHyoungOh** [comment]
Delete functionality is added to the "post" (comment and/or file) an invitee can make to their reservation.

Following what Don said, posts are limited to 1 per person per reservation.
